#!/bin/sh

ACTION=$1
ID=2595
TIMEOUT=1500 # 1.5 Seconds

if [ "$ACTION" = "up" ]; then
    pamixer -i 5
    ICON="audio-volume-high-symbolic"
elif [ "$ACTION" = "down" ]; then
    pamixer -d 5
    ICON="audio-volume-medium-symbolic"
elif [ "$ACTION" = "mute" ]; then
    pamixer -t
    if pamixer --get-mute | grep -q "true"; then
        dunstify -a "OSD" -r "$ID" -t "$TIMEOUT" -i "audio-volume-muted-symbolic" "Muted"
        exit
    else
        ICON="audio-volume-high-symbolic"
    fi
fi

VOL=$(pamixer --get-volume)
dunstify -a "OSD" -r "$ID" -t "$TIMEOUT" -h int:value:"$VOL" -i "$ICON" "Volume: $VOL%"
