#!/bin/sh


TYPE=$1
DIR=$2
TIMEOUT=1500

if [ "$TYPE" = "kbd" ]; then
    DEVICE='--device=*::kbd_backlight'
    ID=2593
    ICON="keyboard-brightness-symbolic"
    NAME="Keyboard"
else
    DEVICE=""
    ID=2594
    ICON="display-brightness-symbolic"
    NAME="Screen"
fi

if [ "$DIR" = "up" ]; then
    brightnessctl $DEVICE set +5%
else
    brightnessctl $DEVICE set 5%-
fi

PERCENT=$(brightnessctl $DEVICE -m | cut -d, -f4 | tr -d %)

dunstify -a "OSD" -r "$ID" -t "$TIMEOUT" -h int:value:"$PERCENT" -i "$ICON" "$NAME: $PERCENT%"
