# Fix colors for Ghostty
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Change prefix to Ctrl+a (easier than Ctrl+b)
set -g prefix C-a
unbind C-b
bind C-a send-prefix
# --- VIM KEYBINDINGS ---
# Use Alt + hjkl to switch panes (No prefix needed!)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Mouse support
set -g mouse on

# One Dark Theme Plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TPM (Keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
